GET http://localhost:3000/api/v1/users

###
GET http://localhost:3000/api/v1/users/c94af2e5-d229-44f6-b1a8-1a2df2c784d8
###
DELETE http://localhost:3000/api/v1/users/fa558a44-3bb9-41b7-960a-11cab21a0087
###
PATCH  http://localhost:3000/api/v1/users/c94af2e5-d229-44f6-b1a8-1a2df2c784d8
content-type: application/json

{
    "name": "James-upd_2/6",
    "birthYear": "1982"
}
###
POST http://localhost:3000/api/v1/users
content-type: application/json

{
  "name": "Jimm3/4-2",
  "email": "email2@email.com",
  "password": "123432",
  "birthYear": "1982"
}
###
POST http://localhost:3000/api/v1/users
content-type: application/json

{
    "name": "Jo",
    "year": "1982"
}
###
